import { CountryDropdown } from 'react-country-region-selector';

export const signInFormFields = [
  {
    tagType: 'regular',
    label: "Company Name *",
    id: "companyName",
    name: "companyName",
    type: "text",
    placeholder: "[Company Name]",
  },
  {
    tagType: 'custom',
    label: "Country *",
    id: "country",
    name: "country",
    country: CountryDropdown,
  },
  {
    tagType: 'masked',
    label: "VAT Nr *",
    id: "vatNr",
    name: "vatNr",
    type: "text",
    placeholder: "xxxxxxxxxxxxx",
    format: "#############",
    mask: "#",
  },
  {
    tagType: 'regular',
    label: "Contact Person *",
    id: "contactPerson",
    name: "contactPerson",
    type: "text",
    placeholder: "[Contact Person]",
  },
  {
    tagType: 'regular',
    label: "Email *",
    id: "email",
    name: "email",
    type: "email",
    placeholder: "[example@gmail.com]",
  },
  {
    tagType: 'masked',
    label: "Phone number",
    id: "telephone",
    name: "telephone",
    type: "text",
    format: "+## ## ### ## ###",
    mask: "#",
  },
  {
    tagType: 'regular',
    label: "Company Website",
    id: "companyWebSite",
    name: "companyWebSite",
    type: "text",
    placeholder: "[Company Website]",
  },
  {
    tagType: 'regular',
    label: "Products of interest?",
    id: "interestProducts",
    name: "interestProducts",
    type: "text",
    placeholder: "[smartphones, computers, drones, consoles, etc]",
  },
  {
    tagType: 'regular',
    label: "Brands of interest?",
    id: "brands",
    name: "brands",
    type: "text",
    placeholder: "[apple, samsung, sony, LG, etc]",
  },
  {
    tagType: 'regular',
    label: "Comment",
    id: "comment",
    name: "comment",
    type: "text",
    placeholder: "",
  },
]
