export const signInFormFields = [
  {
    tagType: 'regular',
    label: "сompanyName",
    id: "companyName",
    name: "companyName",
    type: "text",
    placeholder: "companyNamePlaceholder",
  },
  {
    tagType: 'regular',
    label: "countryName",
    id: "countryName",
    name: "countryName",
    type: "text",
    placeholder: "countryNamePlaceholder",
  },
  {
    tagType: 'masked',
    label: "vatNr",
    id: "vatNr",
    name: "vatNr",
    type: "text",
    placeholder: "xxxxxxxxxxxxx",
    format: "#############",
    mask: "#",
  },
  {
    tagType: 'regular',
    label: "сontactPerson",
    id: "contactPerson",
    name: "contactPerson",
    type: "text",
    placeholder: "сontactPersonPlaceholder",
  },
  {
    tagType: 'regular',
    label: "email",
    id: "email",
    name: "email",
    type: "email",
    placeholder: "emailPlaceholder",
  },
  {
    tagType: 'regular',
    label: "password",
    id: "password",
    name: "password",
    type: "text",
    placeholder: "passwordPlaceholder",
  },
  {
    tagType: 'masked',
    label: "phoneNumber",
    id: "telephone",
    name: "telephone",
    type: "text",
    format: "+## ##########",
    mask: "#",
  },
  {
    tagType: 'regular',
    label: "companyWebsite",
    id: "companyWebsite",
    name: "companyWebsite",
    type: "text",
    placeholder: "companyWebsitePlaceholder",
  },
  {
    tagType: 'regular',
    label: "productsOfInterest",
    id: "interestProducts",
    name: "interestProducts",
    type: "text",
    placeholder: "productsOfInterestPlaceholder",
  },
  {
    tagType: 'regular',
    label: "brandsOfInterest",
    id: "brands",
    name: "brands",
    type: "text",
    placeholder: "brandsOfInterestPlaceholder",
  },
  {
    tagType: 'regular',
    label: "comment",
    id: "comment",
    name: "comment",
    type: "text",
    placeholder: "",
  },
]
